import {
  ConfigurationApplication, AuthorizationService, AuthorizationRequest, ApplicationError, AuthorizationError, DomainInvariantError, NotFoundError,
  InMemoryConfigurationRepository, InMemoryRepository, InMemoryAuditSink, InMemoryEventPublisher, SequenceIdGenerator, FixedClock,
  createTenant, createOrganization, createUnit, configurationScopeKey, sameConfigurationScope, createConfiguration
} from "../src/index.js";
function assert(value:unknown,message:string):asserts value { if(!value) throw new Error("Assertion failed: "+message); }
async function rejects(factory:()=>Promise<unknown>,ErrorType:Function,message:string):Promise<void> { try { await factory(); throw new Error("Expected rejection: "+message); } catch(error) { if(!(error instanceof ErrorType)) throw error; } }
class Policy implements AuthorizationService {
  readonly requests:AuthorizationRequest[]=[];
  constructor(private readonly denied:Set<string>=new Set()) {}
  async can(request:AuthorizationRequest):Promise<boolean> { this.requests.push(request); return !this.denied.has(request.action); }
}
const organizations=new InMemoryRepository<any>(),units=new InMemoryRepository<any>();
const tenantA=createTenant({id:"tenant-a",name:"Tenant A"}),tenantB=createTenant({id:"tenant-b",name:"Tenant B"});
const orgA=createOrganization({id:"org-a",tenantId:tenantA.id,name:"Org A"},tenantA),orgB=createOrganization({id:"org-b",tenantId:tenantB.id,name:"Org B"},tenantB);
const unitA=createUnit({id:"unit-a",tenantId:tenantA.id,organizationId:orgA.id,name:"Unit A"},orgA),unitB=createUnit({id:"unit-b",tenantId:tenantB.id,organizationId:orgB.id,name:"Unit B"},orgB);
await organizations.save(orgA); await organizations.save(orgB); await units.save(unitA); await units.save(unitB);
const configs=new InMemoryConfigurationRepository(),audit=new InMemoryAuditSink(),events=new InMemoryEventPublisher(),policy=new Policy();
const app=new ConfigurationApplication({ids:new SequenceIdGenerator("config"),clock:new FixedClock("2026-10-08T00:00:00.000Z"),authorization:policy,audit,events,configurations:configs,organizations,units});
const tenantCtx={scope:"tenant" as const,tenantId:tenantA.id,actorUserId:"admin-a",correlationId:"corr-config"};
const tenantBContext={scope:"tenant" as const,tenantId:tenantB.id,actorUserId:"admin-b"};
const orgCtx={scope:"tenant" as const,tenantId:tenantA.id,organizationId:orgA.id,actorUserId:"org-admin"};
const unitCtx={scope:"tenant" as const,tenantId:tenantA.id,organizationId:orgA.id,unitId:unitA.id,actorUserId:"unit-admin"};
const tenantScope={level:"tenant" as const,tenantId:tenantA.id},orgScope={level:"organization" as const,tenantId:tenantA.id,organizationId:orgA.id};
const unitScope={level:"unit" as const,tenantId:tenantA.id,organizationId:orgA.id,unitId:unitA.id},moduleScope={level:"module" as const,tenantId:tenantA.id,moduleId:"module-alpha"};
const created=await app.create(tenantCtx,{key:"feature.flag",value:{enabled:true,threshold:3},scope:tenantScope});
assert(created.id.length>0,"stable identity assigned");
assert((await app.getById(tenantCtx,{id:created.id,scope:tenantScope})).key==="feature.flag","read by identity");
assert((await app.getByKey(tenantCtx,{key:"feature.flag",scope:tenantScope})).id===created.id,"read by key in exact scope");
const updated=await app.update(tenantCtx,{id:created.id,scope:tenantScope,value:{enabled:false,threshold:5}});
assert((updated.value as {enabled:boolean}).enabled===false,"update changes value");
assert(updated.id===created.id && updated.scope.level==="tenant" && updated.key==="feature.flag","update preserves identity, key and scope");
await rejects(()=>app.create(tenantCtx,{key:"feature.flag",value:true,scope:tenantScope}),ApplicationError,"duplicate key rejected");
assert((await app.getByKey(tenantCtx,{key:"feature.flag",scope:tenantScope})).id===created.id,"duplicate did not replace configuration");
const orgConfig=await app.create(tenantCtx,{key:"feature.flag",value:"organization-value",scope:orgScope});
const unitConfig=await app.create(tenantCtx,{key:"feature.flag",value:"unit-value",scope:unitScope});
const moduleConfig=await app.create(tenantCtx,{key:"feature.flag",value:"module-value",scope:moduleScope});
assert(orgConfig.id!==unitConfig.id && unitConfig.id!==moduleConfig.id,"same key has distinct identity across scopes");
assert((await app.getByKey(orgCtx,{key:"feature.flag",scope:orgScope})).id===orgConfig.id,"organization scope read");
assert((await app.getByKey(unitCtx,{key:"feature.flag",scope:unitScope})).id===unitConfig.id,"unit scope read");
assert((await app.getByKey(tenantCtx,{key:"feature.flag",scope:moduleScope})).id===moduleConfig.id,"module scope read");
await rejects(()=>app.getById(tenantBContext,{id:created.id,scope:tenantScope}),DomainInvariantError,"cross-tenant scope rejected");
await rejects(()=>app.getById(tenantCtx,{id:orgConfig.id,scope:tenantScope}),NotFoundError,"identity cannot bypass stored scope");
await rejects(()=>app.getByKey(orgCtx,{key:"feature.flag",scope:tenantScope}),DomainInvariantError,"organization context cannot widen to tenant scope");
await rejects(()=>app.getByKey(unitCtx,{key:"feature.flag",scope:orgScope}),DomainInvariantError,"unit context cannot widen to organization scope");
await rejects(()=>app.create(tenantCtx,{key:"cross-org",value:true,scope:{level:"organization",tenantId:tenantA.id,organizationId:orgB.id}}),DomainInvariantError,"organization cannot cross tenant");
await rejects(()=>app.create(tenantCtx,{key:"cross-unit",value:true,scope:{level:"unit",tenantId:tenantA.id,organizationId:orgA.id,unitId:unitB.id}}),DomainInvariantError,"unit cannot cross organization and tenant");
const beforeCount=configs.snapshot().length,beforeAudit=audit.snapshot().length,beforeEvents=events.snapshot().length;
const platformScope={level:"platform" as const};
await rejects(()=>app.create(tenantCtx,{key:"global",value:true,scope:platformScope}),ApplicationError,"platform create rejected");
await rejects(()=>app.getByKey(tenantCtx,{key:"global",scope:platformScope}),ApplicationError,"platform key read rejected");
await rejects(()=>app.getById(tenantCtx,{id:"missing",scope:platformScope}),ApplicationError,"platform identity read rejected");
await rejects(()=>app.update(tenantCtx,{id:created.id,scope:platformScope,value:true}),ApplicationError,"platform update rejected");
assert(configs.snapshot().length===beforeCount && audit.snapshot().length===beforeAudit && events.snapshot().length===beforeEvents,"platform rejection has no persistence or success side effects");
const deniedPolicy=new Policy(new Set(["configuration.create","configuration.read","configuration.update"]));
const deniedAudit=new InMemoryAuditSink(),deniedEvents=new InMemoryEventPublisher(),deniedConfigs=new InMemoryConfigurationRepository();
const deniedApp=new ConfigurationApplication({ids:new SequenceIdGenerator("denied"),clock:new FixedClock("2026-10-08T00:00:00.000Z"),authorization:deniedPolicy,audit:deniedAudit,events:deniedEvents,configurations:deniedConfigs,organizations,units});
await rejects(()=>deniedApp.create(tenantCtx,{key:"denied",value:true,scope:tenantScope}),AuthorizationError,"denied create");
await rejects(()=>deniedApp.getById(tenantCtx,{id:created.id,scope:tenantScope}),AuthorizationError,"denied read");
await rejects(()=>deniedApp.update(tenantCtx,{id:created.id,scope:tenantScope,value:false}),AuthorizationError,"denied update");
assert(deniedConfigs.snapshot().length===0 && deniedAudit.snapshot().length===0 && deniedEvents.snapshot().length===0,"denied operations have no persistence or success side effects");
const auditBefore=audit.snapshot().length,eventBefore=events.snapshot().length;
await rejects(()=>app.getById(tenantCtx,{id:"missing-config",scope:tenantScope}),NotFoundError,"missing identity");
await rejects(()=>app.create(tenantCtx,{key:"invalid-json",value:undefined as never,scope:tenantScope}),Error,"non-JSON value rejected");
assert(audit.snapshot().length===auditBefore && events.snapshot().length===eventBefore,"failed reads do not audit or publish success");
assert(audit.snapshot().length===5 && events.snapshot().length===5,"each successful create/update emits audit and event");
assert(policy.requests.every(request=>Array.isArray(JSON.parse(request.resource)) && (JSON.parse(request.resource) as unknown[])[0]==="configuration"),"authorization receives explicit structured scope resource");
console.log("PASS configuration application, scope isolation, authorization, platform rejection and side-effect invariants");

const collisionScopeA={level:"organization" as const,tenantId:"tenant:a",organizationId:"b"};
const collisionScopeB={level:"organization" as const,tenantId:"tenant",organizationId:"a:b"};
assert(configurationScopeKey(collisionScopeA)!==configurationScopeKey(collisionScopeB),"delimiter-containing scope identifiers have distinct canonical keys");
assert(!sameConfigurationScope(collisionScopeA,collisionScopeB),"delimiter-containing scopes compare as different");
const collisionRepo=new InMemoryConfigurationRepository();
await collisionRepo.save(createConfiguration({id:"collision-a",key:"same.key",value:{owner:"A"},scope:collisionScopeA}));
await collisionRepo.save(createConfiguration({id:"collision-b",key:"same.key",value:{owner:"B"},scope:collisionScopeB}));
assert((await collisionRepo.getByKeyAndScope("same.key",collisionScopeA))?.id==="collision-a","repository lookup finds first structurally distinct scope");
assert((await collisionRepo.getByKeyAndScope("same.key",collisionScopeB))?.id==="collision-b","repository lookup does not collide across delimiter-containing scopes");
const resourceOrgA=createOrganization({id:"org:x:y",tenantId:tenantA.id,name:"Colon Org A"},tenantA);
const resourceOrgB=createOrganization({id:"org:x",tenantId:tenantA.id,name:"Colon Org B"},tenantA);
const resourceUnitA=createUnit({id:"z",tenantId:tenantA.id,organizationId:resourceOrgA.id,name:"Colon Unit A"},resourceOrgA);
const resourceUnitB=createUnit({id:"y:z",tenantId:tenantA.id,organizationId:resourceOrgB.id,name:"Colon Unit B"},resourceOrgB);
await organizations.save(resourceOrgA); await organizations.save(resourceOrgB);
await units.save(resourceUnitA); await units.save(resourceUnitB);
await app.create(tenantCtx,{key:"authorization.resource.collision",value:"A",scope:{level:"unit",tenantId:tenantA.id,organizationId:resourceOrgA.id,unitId:resourceUnitA.id}});
const resourceA=policy.requests[policy.requests.length-1].resource;
await app.create(tenantCtx,{key:"authorization.resource.collision",value:"B",scope:{level:"unit",tenantId:tenantA.id,organizationId:resourceOrgB.id,unitId:resourceUnitB.id}});
const resourceB=policy.requests[policy.requests.length-1].resource;
assert(resourceA!==resourceB,"authorization resource encoding distinguishes delimiter-containing identifiers");
const mutationRepo=new InMemoryConfigurationRepository();
const inputValue={nested:{enabled:true,labels:["original","stable"]}};
const mutableInput=createConfiguration({id:"mutation-config",key:"mutation.key",value:inputValue,scope:tenantScope});
await mutationRepo.save(mutableInput);
inputValue.nested.enabled=false;
inputValue.nested.labels.push("changed-after-save");
(mutableInput.value as {nested:{enabled:boolean;labels:string[]}}).nested.labels[0]="mutated-entity-after-save";
let persisted=await mutationRepo.getById("mutation-config");
assert((persisted?.value as {nested:{enabled:boolean;labels:string[]}}).nested.enabled===true,"mutating save input does not mutate persisted nested object");
assert((persisted?.value as {nested:{enabled:boolean;labels:string[]}}).nested.labels.join(",")==="original,stable","mutating save input does not mutate persisted array");
(persisted!.value as {nested:{enabled:boolean;labels:string[]}}).nested.enabled=false;
(persisted!.value as {nested:{enabled:boolean;labels:string[]}}).nested.labels.push("changed-after-getById");
const byKeyAfterIdMutation=await mutationRepo.getByKeyAndScope("mutation.key",tenantScope);
assert((byKeyAfterIdMutation?.value as {nested:{enabled:boolean;labels:string[]}}).nested.enabled===true,"mutating getById result does not mutate persisted object");
assert((byKeyAfterIdMutation?.value as {nested:{enabled:boolean;labels:string[]}}).nested.labels.join(",")==="original,stable","mutating getById result does not mutate persisted array");
(byKeyAfterIdMutation!.value as {nested:{enabled:boolean;labels:string[]}}).nested.labels[1]="mutated-through-key-result";
const byIdAfterKeyMutation=await mutationRepo.getById("mutation-config");
assert((byIdAfterKeyMutation?.value as {nested:{enabled:boolean;labels:string[]}}).nested.labels.join(",")==="original,stable","mutating getByKeyAndScope result does not mutate persisted array");
const snapshot=mutationRepo.snapshot();
(snapshot[0].value as {nested:{enabled:boolean;labels:string[]}}).nested.labels.push("mutated-snapshot");
assert(((await mutationRepo.getById("mutation-config"))?.value as {nested:{enabled:boolean;labels:string[]}}).nested.labels.join(",")==="original,stable","snapshot also returns defensive copies");
await mutationRepo.save(createConfiguration({id:"mutation-config",key:"mutation.key",value:{nested:{enabled:false,labels:["updated"]}},scope:tenantScope}));
assert(((await mutationRepo.getById("mutation-config"))?.value as {nested:{enabled:boolean;labels:string[]}}).nested.labels[0]==="updated","valid update persists a defensive copy");
await rejects(()=>mutationRepo.save(createConfiguration({id:"mutation-config",key:"changed.key",value:true,scope:tenantScope})),Error,"repository prevents identity key mutation");
await rejects(()=>mutationRepo.save(createConfiguration({id:"mutation-config",key:"mutation.key",value:true,scope:orgScope})),Error,"repository prevents identity scope mutation");
console.log("PASS scope-key collision regressions and defensive-copy repository invariants");

const protoSafeInput:Record<string,unknown>={nested:{safe:true}};
Object.defineProperty(protoSafeInput,"__proto__",{value:{preserved:"proto-data",nested:{marker:7}},enumerable:true,configurable:true,writable:true});
const protoSafeCreated=createConfiguration({id:"proto-safe-config",key:"proto.safe",value:protoSafeInput as never,scope:tenantScope});
const ownProto=(value:unknown):Record<string,unknown>=>{
  assert(value!==null && typeof value==="object" && !Array.isArray(value),"expected a JSON object");
  return value as Record<string,unknown>;
};
const createdProtoValue=ownProto(protoSafeCreated.value);
assert(Object.prototype.hasOwnProperty.call(createdProtoValue,"__proto__"),"createConfiguration preserves own __proto__ property");
assert((ownProto(createdProtoValue["__proto__"])).preserved==="proto-data","createConfiguration preserves __proto__ property value");
assert(Object.getPrototypeOf(createdProtoValue)===Object.prototype,"copying __proto__ does not change destination prototype");
const protoSafeRepo=new InMemoryConfigurationRepository();
await protoSafeRepo.save(protoSafeCreated);
const savedProtoValue=ownProto((await protoSafeRepo.getById("proto-safe-config"))!.value);
assert(Object.prototype.hasOwnProperty.call(savedProtoValue,"__proto__"),"save/getById preserves own __proto__ property");
assert((ownProto(savedProtoValue["__proto__"])).preserved==="proto-data","save/getById preserves __proto__ value");
assert(Object.getPrototypeOf(savedProtoValue)===Object.prototype,"save/getById retains ordinary object prototype");
const keyedProtoValue=ownProto((await protoSafeRepo.getByKeyAndScope("proto.safe",tenantScope))!.value);
assert(Object.prototype.hasOwnProperty.call(keyedProtoValue,"__proto__"),"getByKeyAndScope preserves own __proto__ property");
assert((ownProto(keyedProtoValue["__proto__"])).preserved==="proto-data","getByKeyAndScope preserves __proto__ value");
assert(Object.getPrototypeOf(keyedProtoValue)===Object.prototype,"getByKeyAndScope retains ordinary object prototype");
(ownProto(savedProtoValue["__proto__"])).preserved="mutated-copy";
assert((ownProto(ownProto((await protoSafeRepo.getById("proto-safe-config"))!.value)["__proto__"])).preserved==="proto-data","mutating returned __proto__ data does not mutate repository state");
console.log("PASS own __proto__ JSON property preservation and prototype safety");
