import { createTenant,createOrganization,createUnit,createIdentity,createUser,createProfessional,createSubject,createRole,createPermission,createRolePermission,createUserRole,createRequestContext,createAuditEntry,createDomainEvent,InMemoryEventPublisher } from "../src/index.js";
function assert(condition:unknown,message:string):asserts condition{if(!condition)throw new Error(`Assertion failed: ${message}`);}
function eq<T>(actual:T,expected:T,message:string):void{if(actual!==expected)throw new Error(`Assertion failed: ${message}. Expected ${String(expected)}, got ${String(actual)}`);}
function run(name:string,test:()=>Promise<void>|void):Promise<void>{return Promise.resolve().then(test).then(()=>console.log(`PASS ${name}`));}
await run("creates a valid tenant",()=>{eq(createTenant({id:"tenant-a",name:"Tenant A"}).id,"tenant-a","tenant id");});
await run("relates organization to tenant",()=>{eq(createOrganization({id:"org-a",tenantId:"tenant-a",name:"Org A"}).tenantId,"tenant-a","organization tenant");});
await run("relates unit to organization",()=>{eq(createUnit({id:"unit-a",organizationId:"org-a",name:"Unit A"}).organizationId,"org-a","unit organization");});
await run("creates explicit tenancy context",()=>{const c=createRequestContext({tenantId:"tenant-a",organizationId:"org-a",unitId:"unit-a",actorUserId:"user-a",correlationId:"corr-1"});eq(c.tenantId,"tenant-a","context tenant");eq(c.correlationId,"corr-1","context correlation");});
await run("keeps identity separate from user",()=>{const i=createIdentity({id:"identity-a",subject:"external-subject-a"});const u=createUser({id:"user-a",tenantId:"tenant-a",identityId:i.id,displayName:"User A"});eq(u.identityId,i.id,"identity association");assert(u.id!==i.id,"identity and user are distinct");});
await run("associates professional",()=>{eq(createProfessional({id:"professional-a",tenantId:"tenant-a",userId:"user-a",organizationId:"org-a"}).userId,"user-a","professional user");});
await run("associates subject",()=>{eq(createSubject({id:"subject-a",tenantId:"tenant-a",organizationId:"org-a",displayName:"Subject A"}).tenantId,"tenant-a","subject tenant");});
await run("supports role and permission relationships",()=>{const r=createRole({id:"role-professional",name:"Professional",architecturalRole:"professional"});const p=createPermission({id:"permission-read-subject",code:"subject.read"});eq(createRolePermission({roleId:r.id,permissionId:p.id}).roleId,r.id,"role permission");eq(createUserRole({userId:"user-a",roleId:r.id,scope:{level:"tenant",tenantId:"tenant-a"}}).scope.level,"tenant","user role scope");});
await run("creates audit entry",()=>{eq(createAuditEntry({id:"audit-1",tenantId:"tenant-a",actorId:"user-a",action:"user.created",resource:"user",resourceId:"user-a",timestamp:"2026-10-08T00:00:00.000Z",correlationId:"corr-1",result:"success"}).correlationId,"corr-1","audit correlation");});
await run("creates and publishes versioned domain event",async()=>{const e=createDomainEvent({eventId:"event-1",eventType:"user.created",version:1,occurredAt:"2026-10-08T00:00:00.000Z",tenantId:"tenant-a",actorId:"user-a",source:"heal-core",correlationId:"corr-1",payload:{userId:"user-a"}});const p=new InMemoryEventPublisher();await p.publish(e);eq(p.snapshot().length,1,"event count");eq(p.snapshot()[0]?.correlationId,"corr-1","event correlation");});
await run("propagates correlation id",()=>{const id="corr-2";const c=createRequestContext({tenantId:"tenant-a",actorUserId:"user-a",correlationId:id});const a=createAuditEntry({id:"audit-2",tenantId:c.tenantId,actorId:c.actorUserId,action:"test",resource:"test",timestamp:"2026-10-08T00:00:00.000Z",correlationId:id,result:"success"});const e=createDomainEvent({eventId:"event-2",eventType:"test.completed",version:1,occurredAt:"2026-10-08T00:00:00.000Z",tenantId:c.tenantId,actorId:c.actorUserId,source:"heal-core",correlationId:id,payload:{}});eq(c.correlationId,a.correlationId,"context/audit");eq(a.correlationId,e.correlationId,"audit/event");});
await run("keeps tenant contexts distinct",()=>{const a=createRequestContext({tenantId:"tenant-a",actorUserId:"user-a"});const b=createRequestContext({tenantId:"tenant-b",actorUserId:"user-b"});assert(a.tenantId!==b.tenantId,"tenant contexts must remain distinct");});
